### ISSUE TITLE
Failed to allocate required memory

### ISSUE THREAD

**Issue by dertin** [Sushipool/nimiq-opencl-miner#2]
```
Platform: NVIDIA CUDA by NVIDIA Corporation
  Device #0: GeForce GTX 560 by NVIDIA Corporation:
    Driver 390.87, OpenCL OpenCL 1.1 CUDA
    7 compute units @ 1701 MHz
    Using 0 MB of global memory, nonces per run: 0
Failed to allocate required memory.
Error: Could not initialize miner.
    at new NanoPoolMiner (/home/dertin/miner-nim/nimiq-opencl-miner/src/NanoPoolMiner.js:29:23)
    at /home/dertin/miner-nim/nimiq-opencl-miner/index.js:67:15
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
    at internal/main/run_main_module.js:21:11
```

**Comment by tomkha** [comment]
try to define in the config
`"memory": [1024]`
or even
`"memory": [512]`
